on: push

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        id: build
        run: |
          cd magisk
          VER=$(grep version= module.prop | cut -d= -f2)
          echo "VER=$VER" >> $GITHUB_OUTPUT
          zip -r "../zygisk-detach-${VER}.zip" .

      - name: Upload module to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: zygisk-detach-${{ steps.build.outputs.VER }}.zip
          release_name: zygisk-${{ steps.build.outputs.VER }}
          tag: ${{ steps.build.outputs.VER }}
          overwrite: true
